Don't use _LIBCPP_TEMPLATE_VIS on libcxx >= 220000
The use of _LIBCPP_TEMPLATE_VIS in libcxx was removed for the 22.0
release. This results in an error when combined with the forward
declarations in meta_fwd.hpp

range-v3-src/include/meta/meta.hpp:3797:25: error: redefinition of
'allocator' as different kind of symbol
 3797 | class META_TEMPLATE_VIS allocator;
      |                         ^
/usr/include/c++/v1/__memory/allocator.h:62:7: note: previous definition
is here
   62 | class allocator

The change that removed support is here:
https://github.com/llvm/llvm-project/pull/134885

With the subsequent version bump here:
https://github.com/llvm/llvm-project/commit/01f36b39bd2475a271bbeb95fb9db8ed65e2d065